### PR TITLE
[WIP] Adds Blur device

### PR DESCRIPTION
**Pull request by Brendonovich**
Much to Mat's dismay, I've made a blur device and many people agree it looks sick. Could use optimisations for sure but is pretty good functionality wise.

### CODE REVIEW

**Comment by mat1jaczyyy** [comment]
image

hold this thought until #138 is 🦀🦀🦀🦀

**Comment by mat1jaczyyy** [comment]
also rebase yourself to 1.5.0 or perish

**Comment by Brendonovich** [comment]
good point

**Comment by mat1jaczyyy** [comment]
fixed it for you

**Pull request closed without merging**
