### PR TITLE
Add Launchpad X and Mini MK3 Support

### LINKED ISSUE #280: Launchpad X Support
So I do not own a launchpad pro or mk2 anymore and switched to midi fighter 64 and have recently have gotten a launchpad x as well. I would love if i were to be able to create my light shows with this plugin on my mf64/lpx in the future??

### PR DESCRIPTION
**Pull request by mat1jaczyyy**
Fixes #280.

TODO:

- [x] Detect X
- [x] Detect Mini MK3
- [x] Warn on old laggy firmware
- [x] Raise Novation USB Driver requirement to 2.15.5
- [x] RGB LED message
- [x] Clear message
- [x] Convert color from 6-bit to 7-bit
- [x] Downmix color for MK2/Pro
- [x] Fix Mode Light showing up as Novation Light
- [x] LaunchpadGrid: MK2, X, All skins

### CODE REVIEW

**Comment by mat1jaczyyy** [comment]
Novation LED is nice, but the inner parts of the logo aren't clickable.

**Comment by rpgaleksy** [comment]
Using Launchpad Pro popout window shows colors only half as bright (7F7F7F looks like 3F3F3F), preview windows is not affected though.

**Comment by rpgaleksy** [comment]
Pattern: Picking a color from the mode light using Ctrl+LeftMouse is not possible in launchpad-x branch (97e0397).

**Comment by mat1jaczyyy** [comment]
Don't think I forgot anything, YOLO

**Pull request merged**
