### PR TITLE
Matrix support

### LINKED ISSUE #381: Matrix Support
Matrixes will need CFW + forced Novation driver for multiclient, waiting for that might a while.

### PR DESCRIPTION
**Pull request by 203Null**
This PR added experimental support for Matrix and Matrix Pro with Matrix OS 2.4 and above.

Fixes #381

### CODE REVIEW

**Comment by mat1jaczyyy** [comment]
Unsure if this will require 1.9 or we can stay as 1.8.x, need to check

**Comment by mat1jaczyyy** [comment]
This doesn't need 1.9 so it will be 1.8.12 if everything is finished before 1.9 features are done

**Comment by mat1jaczyyy** [comment]
The big leftover TODOs:

- [ ] Fully figure out and finalize firmware version comparison
- [ ] Matrix Standard is not handled at all yet
- [ ] Proper warning/error messages for old/unsupported Matrix firmware with permalinks to updates
- [ ] LaunchpadGrid UI control Matrix and MatrixPro models (this can be postponed to later versions, it's more of a nice to have than a requirement)

**Comment by 203Null** [comment]
> Fully figure out and finalize firmware version comparison
Pushed a new parser. This will be the MatrixOS SysEx version format from 2.4.1 and onward. I left a versionStr creation code in there to help you understand how it works. 

> Matrix Standard is not handled at all yet
Device ID added. Pending detail implementation.

**Comment by mat1jaczyyy** [comment]
I couldn't test on my FE because of bugged firmware, but I think it's good to merge

**Pull request merged**
