### PR TITLE
[WIP] Undo/Redo Rewrite

### LINKED ISSUE #179: Rewrite Undo/Redo
- [x] UndoEntry base class
- [x] Generalize Path stuff into PathUndoEntry
- [x] Rewrite UndoManager
- [x] Rewrite Add actions

### PR DESCRIPTION
**Pull request by mat1jaczyyy**
Fixes #179.

### CODE REVIEW

**Comment by mat1jaczyyy** [comment]
@Brendonovich @rpgaleksy I added a LegacyUndoEntry temporarily so old system undo stuff doesn't error out anymore, meaning this is compilable. In the Undo History, any old system undo entry will have a [Legacy] prefix. Please try out all the non-legacy undo events.

If you need a list of all rewritten events, you can search for `UndoEntry:` in VS Code which should give you a list of all individual entry classes.

**Comment by rpgaleksy** [comment]
> make sure not to overwrite future undo events

The old system is not too compatible with the new system, trying to dispose future undo events while the referenced object has already been deleted causes crashing.

**Comment by mat1jaczyyy** [comment]
@rpgaleksy Dispose calls no longer resolve Path, so that should be fixed and compatible with Legacy stuff

**Comment by mat1jaczyyy** [comment]
@Brendonovich @rpgaleksy This is finished apart from Output device having one `// TODO` that I need to work out, please test everything else.

You can quickly find all Undo entry classes by searching for `UndoEntry:` in VS Code.

**Comment by mat1jaczyyy** [comment]
Seems like most things are fixed. One quirk remains...

https://github.com/mat1jaczyyy/apollo-studio/blob/undo-redo-rewrite/Apollo/Devices/Output.cs#L48-L53

**Comment by mat1jaczyyy** [comment]
Everything's done 🎉 
One last review please @rpgaleksy @Brendonovich?

**Comment by mat1jaczyyy** [comment]
here goes nothing

**Pull request merged**
